repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    # -   id: ...

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.46.2
    hooks:
    -   id: golangci-lint